## PyTorch Basics: Tensors and Gradients

In [1]:
import torch

In [2]:
#tensor -> n-dimensional array
t1 = torch.tensor(4.)           #4. -> decimal 4.0
t1

tensor(4.)

In [3]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [4]:
#matrix
t3 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
#3D array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [6]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [7]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [8]:
print(t3)
t3.shape

tensor([[1, 2],
        [3, 4],
        [5, 6]])


torch.Size([3, 2])

In [9]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

### Tensor operations and gradients

In [10]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [11]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [12]:
#compute derivatives
y.backward()

In [13]:
#display gradients
print(f"dy/dx: {x.grad}")       #nothing since x is constant, param is not set
print(f"dy/dw: {w.grad}")       #we get x when derived (x*w + b -> w is variable here; derivation gives x whose value is 3)
print(f"dy/db: {b.grad}")       #derivation wrt b is 1 since b disappears and it has no constant associated with it

dy/dx: None
dy/dw: 3.0
dy/db: 1.0
