## PyTorch Basics: Tensors and Gradients

In [2]:
import torch

In [3]:
#tensor -> n-dimensional array
t1 = torch.tensor(4.)           #4. -> decimal 4.0
t1

tensor(4.)

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
#matrix
t3 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
#3D array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [7]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [8]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [9]:
print(t3)
t3.shape

tensor([[1, 2],
        [3, 4],
        [5, 6]])


torch.Size([3, 2])

In [10]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])