## Linear Regression with PyTorch

In [3]:
import numpy as np
import torch

In [4]:
#training data
#inputs -> temp, humidity, rainfall
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 76, 90]], dtype='float32')

#targets -> apples, oranges
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [5]:
#inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

#### Model

In [6]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.7623,  0.1179,  1.1031],
        [-0.2627,  0.0052, -0.4849]], requires_grad=True)
tensor([ 0.8393, -0.3225], requires_grad=True)


In [7]:
#model
def model(x):
    return x @ w.t() + b        #@ -> matrix multiplication in pytorch; t-> transpose

In [8]:
#predictions
preds = model(inputs)
print(preds)

tensor([[  0.5220, -39.9988],
        [ 12.4405, -54.8003],
        [ 14.2925, -50.6009],
        [-31.0305, -44.8315],
        [ 56.4757, -61.6915]], grad_fn=<AddBackward0>)


In [9]:
#compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
#loss function (mse)
def mse(t1, t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [11]:
loss = mse(preds, targets)
loss.sqrt()

tensor(115.3894, grad_fn=<SqrtBackward0>)

In [12]:
loss.backward()

In [13]:
print(w)
print(w.grad)

tensor([[-0.7623,  0.1179,  1.1031],
        [-0.2627,  0.0052, -0.4849]], requires_grad=True)
tensor([[ -5603.5288,  -5919.4448,  -3799.1416],
        [-11799.1104, -12586.8359,  -8928.0039]])


In [14]:
#resetting gradients back to 0 to prevent adding up
w.grad.zero_()
b.grad.zero_()
print(w.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


##### Gradient Descent

In [15]:
preds = model(inputs)
preds

tensor([[  0.5220, -39.9988],
        [ 12.4405, -54.8003],
        [ 14.2925, -50.6009],
        [-31.0305, -44.8315],
        [ 56.4757, -61.6915]], grad_fn=<AddBackward0>)

In [16]:
loss = mse(preds, targets)
loss

tensor(13314.7207, grad_fn=<DivBackward0>)

In [17]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -5603.5288,  -5919.4448,  -3799.1416],
        [-11799.1104, -12586.8359,  -8928.0039]])
tensor([ -65.6600, -142.3846])


In [18]:
#adjust weights and reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [19]:
#new weights and biases
print(w)
print(b)

tensor([[-0.7062,  0.1770,  1.1411],
        [-0.1447,  0.1311, -0.3956]], requires_grad=True)
tensor([ 0.8399, -0.3211], requires_grad=True)


In [20]:
#re-calculate loss
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(9136.7246, grad_fn=<DivBackward0>)

In [21]:
#training with 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [22]:
#new loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(150.9475, grad_fn=<DivBackward0>)


In [23]:
preds

tensor([[ 55.7858,  75.4075],
        [ 84.0125, 100.4428],
        [105.2001, 135.3858],
        [ 21.7346,  58.5621],
        [117.5363,  94.5383]], grad_fn=<AddBackward0>)

In [24]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

##### Linear regression using PyTorch built-ins

In [25]:
import torch.nn as nn

In [26]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)