## Linear Regression with PyTorch

In [1]:
import numpy as np
import torch

In [2]:
#training data
#inputs -> temp, humidity, rainfall
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 76, 90]], dtype='float32')

#targets -> apples, oranges
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [3]:
#inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

#### Model

In [4]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.1658, -2.0507, -1.3937],
        [ 0.7885,  1.3358,  2.9509]], requires_grad=True)
tensor([1.0693, 2.7515], requires_grad=True)


In [5]:
#model
def model(x):
    return x @ w.t() + b        #@ -> matrix multiplication in pytorch; t-> transpose

In [6]:
#predictions
preds = model(inputs)
print(preds)

tensor([[-281.3634,  276.7025],
        [-374.6814,  380.9174],
        [-455.9887,  421.5042],
        [-257.5924,  249.8050],
        [-360.6619,  424.2647]], grad_fn=<AddBackward0>)


In [7]:
#compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
#loss function (mse)
def mse(t1, t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [9]:
loss = mse(preds, targets)
loss.sqrt()

tensor(358.8889, grad_fn=<SqrtBackward0>)

In [10]:
#gradient descent
loss.backward()

In [11]:
print(w)
print(w.grad)

tensor([[-1.1658, -2.0507, -1.3937],
        [ 0.7885,  1.3358,  2.9509]], requires_grad=True)
tensor([[-35325.9297, -37402.5156, -25818.8145],
        [ 21686.2031,  21898.4199,  15776.7559]])


In [12]:
#resetting gradients back to 0 to prevent adding up
w.grad.zero_()
b.grad.zero_()
print(w.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
